### ISSUE TITLE
Initial review

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/occupancy#3]
These are first impressions / comments on the package. First of all, again, many many thanks for assembling this so quickly. A few notes below - will make sure to write further reviews as proper PR reviews. Meanwhile, filling this up as it goes. I'll comment when finished.

### README

It may be useful to provide the instruction to build the package with vignettes:
```r
remotes::install_github("reconhub/occupancy", build_vignettes = TRUE, force = TRUE)
```

Also, the command to load the vignette should read:
```r
vignette("overview", package = "occupancy")
```

### `misc.R`

I am not sure if this is needed, but may be wrong:

* the `ìmportFrom` tags should not be needed; imports in the `NAMESPACE` should be added  automatically by `roxygen2` when running `devtools::document()` as long as the imported functions are referred explicitly e.g. `foo::bar()`
* I don't think we should export `projections::build_projections` and `incidence::incidence`; this should be handled as the point before

### `project_beds.R`

* if you add `Roxygen: list(markdown = TRUE)` to `DESCRIPTION` you can then use markdown syntax for the documentation, so e.g. `\code{foo}` can be replaced with `` `foo` `` (same for links).
* add both our names as authors, yours first
* in the examples, we may need to enclose code within:
```r
if (require(incidence)) {
...
}
if (require(projections)) {
...
}
## note: ggplot2 may be needed too if we customise graphs
```
* labels of y-axes for plots should indicate the corresponding quantity, when it is not 'incidence' but 'numbers of beds needed', so maybe add `+ labs(title = "..." , y = ...)`?

### Graphics

Currently we rely on `projections::plot` which is fine, but the y-axis will systematically default to `incidence`, which is wrong (if anything, bed occupancy is a *prevalence* rather than an *incidence*). A simple fix, which could be useful in the future if we want further customisation, would be to add a class on top of `projections` to the output of `project_beds` and define a custom `plot` method for this class, which wraps around `projections:::plot.projections`, fixing the label of the y axis?

### Tests

* may need to load somewhere the packages used in the tests (*incidence* and *projections*)
* suggest adding test on: 
    + `class` of the output
    + expected `error` messages
    + test `simulate_occupancy` directly, even if the function itself is not exported
    + test graphical outputs using `vdiffr`

<br>
**Review finished :) **

**Comment by TimTaylor** [comment]
Cheers.  

I'll start implementing the changes and get you to review the PR.  As with your review I will keep editing this post as I work through them.  Will ping you when finished.  For reference the changes will be on the [reviewchanges](https://github.com/reconhub/occupancy/tree/reviewchanges) branch.

# README
Changed as per review comments.

# misc.R (now called rexports.R)
> * the `ìmportFrom` tags should not be needed; imports in the `NAMESPACE` should be added  automatically by `roxygen2` when running `devtools::document()` as long as the  imported functions are referred explicitly e.g. `foo::bar()`
> * I don't think we should export `projections::build_projections` and `incidence::incidence`; this should be handled as the point before

* The first function I was using `importFrom` (`methods::is`) is not even used so that was an error on my part.  The other uses are necessary for reexporting `incidence` and `build_projections` from the relevant packages.  I've never quite worked out why the additional `importFrom` is needed but for some reason it is (see https://github.com/tidyverse/dplyr/blob/master/R/reexport-tibble.r for another example of this).  I felt reexporting functions was better than forcing the user to make the extra calls to `library(incidence)` and `library(projections)` before they could make use of the `project_beds` function.
* To make the intent clearer I've renamed `misc.R` to `reexports.R`

# project_beds.R
> * if you add `Roxygen: list(markdown = TRUE)` to `DESCRIPTION` you can then use markdown syntax for the documentation, so e.g. `\code{foo}` can be replaced with `` `foo` `` (same for links).

I didn't know that. Changed.

> * add both our names as authors, yours first

Changed.

> * in the examples, we may need to enclose code within:
> 
> ```r
> if (require(incidence)) {
> ...
> }
> if (require(projections)) {
> ...
> }
> ## note: ggplot2 may be needed too if we customise graphs
> ```

As I've reexported `incidence::incidence` the call directly to that package in the example was unnecessary.  I've corrected this in the PR.  Ignoring ggplot2 for the moment, this means that the only function that could cause trouble is `plot` which I think (and could definitely be wrong) is treated somewhat differently as it's a generic and as long as projections is imported (which it already is) this should be ok.  Once I've finished the changes I'll pass the package through Rhub to check everything prior to submission.

# Graphics
> Currently we rely on `projections::plot` which is fine, but the y-axis will systematically default to `incidence`, which is wrong (if anything, bed occupancy is a _prevalence_ rather than an _incidence_). A simple fix, which could be useful in the future if we want further customisation, would be to add a class on top of `projections` to the output of `project_beds` and define a custom `plot` method for this class, which wraps around `projections:::plot.projections`, fixing the label of the y axis?

Let me think about this a little more.  Adding a class will work nicely but I'm wondering if a change should be made to the projections plot method to allow labels/title arguments.  Thoughts?

# Tests
> * may need to load somewhere the packages used in the tests (_incidence_ and _projections_)

I've removed the direct call `incidence::incidence` and replaced with `incidence`.  As this and build_projections are reexported there is no need to load the additional packages for tests.

> * suggest adding test on:
>    * `class` of the output

Done

> * suggest adding test on:
>    * expected `error` messages

Mostly done now.  One or two are already actually picked up by the incidence package (so we can probably remove).  A couple of other tests should probably be caught upstream as well.  I'll create a separate issue to keep track of where we are with testing in regards to this.

> * suggest adding test on:
>    * test `simulate_occupancy` directly, even if the function itself is not exported

I think we are ok without this additional testing.  The bulk of `project_beds` is really the `lapply` wrapper around simulate_occupancy so any additional tests I'd write would actually be relatively duplicative.  Happy to revisit this if needed.

> * suggest adding test on:
>    * test graphical outputs using vdiffr

Let me look in to vdiffr.  

** That completes my response to the initial review.  I will raise separate issues to track the Graphics issue (plots) and for general test coverage and a separate one for integration of vdiffr.  Pull request coming your way **

**Comment by TimTaylor** [comment]
I've had a little think about plotting and I still think it would be good to make plot.projections more generic and accept extra arguments for plotting.  There is then still a question of whether we would expect an `occupancy` class to have different behaviour to a `projections` class.  If so then it may be worth introducing an occupancy class.  If not, perhaps we hold off for the time being.

If you do want an occupancy class then it would help to add a `...` argument to the `"[".projections` method within the projections package.  Currently this is missing which means we would have to add additional methods within this package rather than be able to utilise `projections` through the fallback in method dispatch.  I can raise a PR if you want..

**Comment by thibautjombart** [comment]
I agree with your suggestions. Great if you can PR on the projections package.

**Comment by TimTaylor** [comment]
Have done a PR on projections (https://github.com/reconhub/projections/pull/25) to make the plot function accept a y-label and title.  If that goes through I'll tweak #5 to adjust plots.
